### ISSUE TITLE
[Game Request] Zelda: Collector's Edition US/JP Versions.

### ISSUE THREAD

**Issue by Xenioxx** [bkacjios/m-overlay#73] opened 2021-02-02 04:20 UTC
Was wondering if it would be possible to add support for Zelda: Collector's Edition (Preferably both English and Japanese versions). Thanks.

**Comment by little512** [comment] 2021-02-04 04:04
Hi @Xenioxx

This one is a difficult one. My attempts at trying to support this game were ultimately put on hold based on complications with how to go about supporting it. The game has different locations in memory where the controller inputs are stored for each game (including the main menu), dynamically switching memory locations would be a challenge and likely a new feature to be added to the program itself.

The short answer: it's possible, just not right now. I'll ask that you keep the issue open for now and I'll keep this thread up to date on my progress with it.

**Comment by little512** [comment] 2021-02-06 05:21
Update: I have experimental support for Zelda Collector's Edition NTSC-U and NTSC-J in [my fork](https://github.com/little512/m-overlay) of m-overlay. I'm pretty sure everything is finished, I just need someone else to test it to make sure we don't have a Works On My Machine:tm: moment.

**Comment by bkacjios** [comment] 2021-02-06 05:48
I gave it a quick test and it seems to work fine for me. Only minor issue I noticed is that the controller struct may be different when in OOT or MM, like if you scroll over to player 2 while moving around the joystick with a controller in port 1 the c-stick will start moving left and right. Probably not a big deal since you only can use port 1 anyway.

**Comment by little512** [comment] 2021-02-06 05:53
> The controller struct may be different when in OOT or MM, like if you scroll over to player 2 while moving around the joystick with a controller in port 1 the c-stick will start moving left and right. Probably not a big deal since you only can use port 1 anyway.

I also noticed this, but I assumed since the game only works with port 1 anyway people wouldn't necessarily be switching the current port. It could be fixed later if necessary but for now it should work as intended.

Another issue I'd like to note is that the controller overlay doesn't necessarily work while games are loading since what determines which game is currently loaded isn't loaded yet, in particular loading Majora's Mask on NTSC-J makes the overlay freak out since it's reading arbitrary memory at that point. Again, probably not a big deal but worth noting this is possible.

**Comment by little512** [comment] 2021-02-09 08:50
@bkacjios I'm going to assume you meant to close this issue since the pull request was merged?

**Comment by bkacjios** [comment] 2021-02-09 09:48
No. I close the issue when I make a release that includes it

**Comment by bkacjios** [comment] 2021-03-18 01:53
https://github.com/bkacjios/m-overlay/releases/tag/v1.7

**Closed by bkacjios** 2021-03-18 01:53 UTC
Labels: suggestion
